spring.application.name=prodigy_fs_01

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/prodigy_fs_01?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Medibook@2026!!

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# STATIC RESOURCES (Frontend)
# ===============================
spring.web.resources.static-locations=file:./frontend/,classpath:/static/

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# JWT
# ===============================
app.jwt.secret=ProdigyFS01SecretKeyForJWTAuthenticationTokenGeneration2026SecureRandomKey
app.jwt.expiration-ms=86400000
